name: myenv
channels:
  - defaults
dependencies:
  - aiohttp==3.8.1
  - beautifulsoup4==4.10.0
  - biopython==1.79
  - dask==2021.11.2
  - dask-ml==1.9.0
  - distributed==2021.11.2
  - json5==0.9.6
  - joblib==1.1.0
  - linecache2==1.0.0
  - matplotlib==3.5.0
  - multiprocessing==0.70.12.2
  - numpy==1.21.2
  - pandas==1.3.4
  - scikit-learn==1.0.1
  - urllib3==1.26.7
  - watchdog==2.1.6
